### ISSUE TITLE
Statusvol themeable

### ISSUE THREAD

**Issue by larsenwork** [srolfe/tweaks#1]
Hi, I'd like to know if statusvol could be made themeable - would like to make it work with my other themes at sb.andreaslarsen.dk :)

**Comment by srolfe** [comment]
Been a while, but I finally picked this tweak back up. The newest version has preliminary theming support, available on: http://cydia.myrepospace.com/chewmieser/

You'll have to uninstall the previous version prior to installing this one.

**Comment by larsenwork** [comment]
cool, I'll look into it :thumbsup:

**Comment by larsenwork** [comment]
tried just replacing the on/off.png's but wouldn't work - it automatically reverted to default
![off](https://cloud.githubusercontent.com/assets/3859425/3212485/2d09eed2-ef60-11e3-8acd-03f418663248.png)
![on](https://cloud.githubusercontent.com/assets/3859425/3212486/2d0c3d86-ef60-11e3-9f58-735baaafe29f.png)

**Comment by larsenwork** [comment]
would be easier to theme if it supported 40px tall images and the spacing (horizontal padding) wasn't added in the code but with the image files

**Comment by srolfe** [comment]
Thanks for the reports, shouldn't take too long to implement them. If you cut your skin images down to 11x11, they should mask properly for the time being, but I'll take a look at these tomorrow.

**Comment by larsenwork** [comment]
Cool - what I'd like to be able to is this:
![img_2887](https://cloud.githubusercontent.com/assets/3859425/3213833/bbf661b4-ef9e-11e3-8f0a-6f8f520d6ac9.png)

And for some of my other statusbar themes too: http://andreaslarsen.dk/statusbar/

I'm not sure but I think putting the resources inside /Library/Application Support/Statusvol would be more "correct" than the documents folder

**Comment by larsenwork** [comment]
Thinking of it it would actually be a lot more versatile if one could use 1 image for each state - so that a statusvol theme required 16 images - that would open op the possibility for circular volume indicators and other creative solutions so a theme could look something like this instead: 

https://dl.dropboxusercontent.com/u/3019777/I%20I%20I%20I%20I.zip

This is also how Apple does for the signal indicators and how the alkaline (themeable battery) tweak works

**Comment by srolfe** [comment]
That seems to be a common request at this point... I'll take a look into it, definitely seems like the right way to go.

**Comment by srolfe** [comment]
![Screenshot](http://i.imgur.com/m8gvA4B.png)

This is essentially implemented at this point, but I had some questions that you might know the answers better for:
1. I'm trying to think of how it'd position the image in the frame. If I have it scale it, then larger images will always fit in that space but smaller images would likely be scaled up... Unless I kept the aspect ratio? If I have it merely center the image, then smaller images fit fine but larger images would probably be chopped.
2. Should spacing from the device top be set on the skin level? I'm thinking of just allowing an area like 20px tall and just letting the skin decide the best use for that space. It's either that or figuring out what matches the surrounding area and limiting it to that, lining up the bar frame with this area. Ideas? Does winterboard have a set limit for statusbar icons?

**Comment by srolfe** [comment]
Actually, I think I'll just set the area to a max of 20px and center the skin area on the statusbar. Should give enough room to be creative.

**Comment by larsenwork** [comment]
Not sure if I've understood the question but the easiest is if all images are 20 pt tall (= 40 px retina) since it's the height of the status bar

**Comment by larsenwork** [comment]
So you'd just have to tell themers to create 16 state images that are 40px tall and call them 1@2x.png etc and 1.png, 2.png etc for non retina and then no scaling will be required at all

**Comment by srolfe** [comment]
Before I throw this up on the repo, wanna give it a shot:

https://www.dropbox.com/s/rzuaedvob1v3klr/com.chewmieser.statusvol_0.0.3-85_iphoneos-arm.deb

(Edit: I think you need to remove the one from the repo in order to install this version)

I've included three base themes, light and dark versions of each theme. Direction is switched to /Library/StatusVol (Alkaline's structure).

I was gonna color on-the-fly, but, IMO it makes more sense to leave full control to the theme designer. Then you can create crazy color themes or whatever.

Let me know if you run into any issues. I still need to downsample some of my themes to non-retina... Not too concerned about it though.

**Comment by larsenwork** [comment]
hi - I've got an exam coming up so won't have time the next two weaks to test stuff, sry :smile:

**Comment by srolfe** [comment]
Ah, no worries. Good luck on the exam, I just released it anyways.

**Comment by larsenwork** [comment]
Cool, I get a database error when trying to upgrade from your repo though

**Comment by larsenwork** [comment]
Never mind - works now. Will try one theme when I get home and report back but looks promising.

Would be cool to be able to adjust the fade delay after adjusting - it should disappear almost instantly if you ask me - I only want the indicator to be visible when I adjust and not 3-5 seconds afterwards but that's just me:)

**Comment by larsenwork** [comment]
I've got a script that automatically creates non retina so don't spend any time on that.

I'd suggest image optimizing (will reduce file size to 1/10) but I can also do that later today.

The tweak looks and works really well!

Let me know if you'd want me to update the icon or some other graphics or help with the depiction on the repo (add repo.andreaslarsen.dk to see how mine looks)

**Comment by srolfe** [comment]
Thanks for the help and the kind words!

I figured I might as well get the repo off of myrepospace, so I threw a new repo online. Just working on depictions at the moment, but the address is: apt.steverolfe.com. Which reminds me that I should add the myrepospace package as a conflict on this package so you don't have to uninstall the old one in order to install the new one...

Either way, things are looking legit. I kept meaning to gitignore those files, so that's all set now and your changes are merged. Thanks for the downsampled images!

Hopefully the couple months was worth the wait haha!

**Comment by srolfe** [comment]
Oh, I'll look into the configurable delay as well. It's just using the stock volume HUD delays at the moment.

**Comment by larsenwork** [comment]
I got a strange pixel error with even width images so I resized them to 225x40 and they displayed correctly - not a major bug but a bit odd.

Sometimes it shows the light version on white background - e.g. when adjusting the volume when inside the settings app.

**Comment by srolfe** [comment]
Odd bug, will look into.

The second one is a definite issue, it's having trouble seeing what colors are being used in the statusbar sometimes. Usually it'll fix itself, but I'm looking into that.

**Comment by larsenwork** [comment]
Cool, maybe ask https://twitter.com/magn2o or other devs that have created statusbar tweaks on how to get statusbar background color
