### ISSUE TITLE
StatusVol crashing device to safe mode when using iOS 8 Quick Reply

### ISSUE THREAD

**Issue by anthonyjr2** [srolfe/tweaks#5]
iPhone 6, iOS 8.1

StatusVol crashes the device to safe mode whenever you try to quick reply to someone. It's been happening to others as well according to reddit.

**Comment by srolfe** [comment]
I saw this issue being reported and narrowed it down to the color changing hooks. Planning on digging into this over the weekend, and fixing the color changing at the same time.

**Comment by srolfe** [comment]
"Fixed" with StatusVol2.
